@startuml sequence 

participant cdrg as "CDRg"
participant brt  as "BRT"
queue       mq   as "Kafka"
participant hrs  as "HRS" 

autonumber
loop 10 записей
    cdrg --> cdrg : Сгенерировать данные о вызове
end
cdrg -> cdrg ++ : Сформировать CDR
cdrg --> cdrg -- : CDR
cdrg --> mq : CDR 
cdrg--
brt -> mq ++ : Получить CDR
mq --> brt -- : CDR
opt Получены данные за следующий месяц
    brt -> hrs ++ : Запросить данные о\nпомесячных тарифах\nGET /tariffs?type=monthly
    hrs --> brt -- : 200 OK + информация\nо помесячных тарифах
    loop Для каждого абонента с помесячным тарифом
        brt --> brt : Списание средств со счета\nи обновление баланса
    end
end
loop Для каждой записи в CDR
    brt -> brt ++ : Авторизация абонента
    brt --> brt -- : Результат авторизации
    alt Не является абонентом "Ромашки"
        brt --> brt : Переход к следующей записи
        else Абонент "Ромашки"
            brt -> brt ++ : Преобразование записи
            brt --> brt -- : Преобразованная запись
            brt --> mq -- : Информация о вызове
            hrs -> mq ++ : Получить данные вызова
            mq --> hrs -- : Данные вызова
            hrs -> hrs ++ : Рассчитать сумму списания 
            hrs --> hrs -- : Сумма списания
            hrs --> mq -- : Запросить списание средств
            brt -> mq ++ : Получить запрос на списание
            mq --> brt -- : Запрос на списание
            brt --> brt : Списание средств
            brt --> brt : Переход к следующей записи
    end
end


@enduml